### ISSUE TITLE
Getting empty responses from a localCall.callSync

### ISSUE THREAD

**Issue by nw0428** [SUSE/salt-netapi-client#165] opened 2016-07-07 20:58 UTC
When I run the following code: `result = localCall.callSync(client, globTarget, saltUser, saltPassword, AuthModule.PAM);` result is an empty map.

**Comment by renner** [comment] 2016-07-08 06:12
Hey @nw0428, we need more information to further debug your issue: what exact type of a call is the `localCall` in your example? Could it possibly be the case that your `globTarget` does not actually match any minions? Does `PAM` authentication work for you otherwise? Please give enough code so that we can actually try to reproduce the issue, thanks!

**Comment by osbominix** [comment] 2017-06-22 21:59
The problem is reproducible if the globTarget does not match any minions. 

Like the example file [Calls.java](https://github.com/SUSE/salt-netapi-client/blob/master/src/test/java/com/suse/salt/netapi/examples/Calls.java) from package com.suse.salt.netapi.examples, 
if both minions("minion1", "minion2") are not running, the value of "grainResults" will be empty.

In this case, it could be helpful to show a warning message. For example, do the validation for the return value of callSync method in class LocalCall?

**Comment by renner** [comment] 2017-07-12 08:13
Closing the issue as this is actually the expected behavior for minions that are either down or minions that are not matching an existing target as clarified in [this comment](4190cde15fca64de79610ade31e92366038b16b8). Feel free to revive it in case you have further questions.

**Closed by renner** 2017-07-12 08:13 UTC
